spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/auth_db
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate.format_sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration # Note: You had 'migrations' before, now it's 'migration'. Ensure this matches your actual folder name.
    baseline-on-migrate: true
    clean-disabled: true
  logging: # This needs to be correctly indented under 'spring'
    level: # This needs to be correctly indented under 'logging'
      org: # This needs to be correctly indented under 'level'
        springframework: # This needs to be correctly indented under 'org'
          security: DEBUG # This needs to be correctly indented under 'springframework'
