spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/grapqldb
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate.format_sql: true
    graphql:
      path: /graphql
      schema:
        locations: classpath:graphql
        printer:
          enabled: true
        introspection:
          enabled: true
      graphiql:
        enabled: true
      cors:
        allowed-origins: "*"
  flyway:
    enabled: true
    locations: classpath:db/migrations
    baseline-on-migrate: true
    clean-disabled: true
  redis:
    host: localhost
    port: 6379
  logging:
    level:
      org:
        springframework:
          security=DEBUG:
